[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

# Redirect default Netlify subdomain to primary domain
# http://awesome-yonath-dee9ce.netlify.com/* http://ericfirth.com/:splat 301!
